Milestone 4: UI
nicolasmarino99/redux-bookstore- pull request #5
Opened 2020-08-28 21:29 UTC by nicolasmarino99

This milestone was focused on adding styles to the components. I did some extra features for making it more functional. 
### **React** ⚛️

#### components 🔌
- Implementation of a  functional progress bar.
- implementation of extra inputs to handle pages info.
### **Redux** 🏪

#### Reducers 🔌
- N/A
#### Actions 🔌
- N/A.
#### Store 🔌
- N/A.

### **Styles**🎨
- Styles added to each component.

2020-08-28 21:30 UTC, nicolasmarino99 commented
I can't fix one stylelint problem.

2020-08-28 21:43 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [ ] The `ADD NEW BOOK` section of your design should have the same width as each book listed above, padding/margin inclusive. Kindly check the given design and ensure your design looks **EXACTLY** the same.

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-08-28 21:43 UTC, suretrust commented on README.md
>  The calculator counts with:
- [ ] Update your readme appropriately, there are still some words like `calculator`.

2020-08-28 21:43 UTC, suretrust commented on README.md
>  [Live version](https://react-calculator99.herokuapp.com)
- [ ] The link in your readme redirects to a calculator, let's ensure the app is available online and add the link to the readme.

2020-08-29 20:34 UTC, shloch approved these changes
## Hello @nicolasmarino99 


The final rendering is great
![book](https://user-images.githubusercontent.com/40712459/91645712-5221af80-ea3f-11ea-83b0-f9cd5211240c.gif)

Happy coding

2020-08-31 15:34 UTC, merged